/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profiles */
        get: operations["profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Versions */
        get: operations["profile_versions_api_profiles__name__versions_get"];
        put?: never;
        /** Create Profile Version */
        post: operations["create_profile_version_api_profiles__name__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{name}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Version */
        get: operations["profile_version_api_profiles__name__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Detail */
        get: operations["task_detail_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Agent */
        post: operations["register_agent_api_tasks__task_id__agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Heartbeat */
        patch: operations["heartbeat_api_tasks__task_id__agents__agent_id__patch"];
        trace?: never;
    };
    "/api/tasks/{task_id}/agents/{agent_id}/conclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Conclude */
        post: operations["conclude_api_tasks__task_id__agents__agent_id__conclude_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/agents/{agent_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish */
        post: operations["finish_api_tasks__task_id__agents__agent_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/agents/{agent_id}/grace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grace */
        post: operations["grace_api_tasks__task_id__agents__agent_id__grace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Archive */
        post: operations["record_archive_api_tasks__task_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/claim_for": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim For */
        post: operations["claim_for_api_tasks__task_id__claim_for_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close */
        post: operations["close_api_tasks__task_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Fact */
        post: operations["post_fact_api_tasks__task_id__facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Intent */
        post: operations["post_intent_api_tasks__task_id__intents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/intents/{intent_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim */
        post: operations["claim_api_tasks__task_id__intents__intent_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/intents/{intent_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release */
        post: operations["release_api_tasks__task_id__intents__intent_id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/intents/{intent_id}/system_close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** System Close */
        post: operations["system_close_api_tasks__task_id__intents__intent_id__system_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object */
        get: operations["get_object_api_tasks__task_id__objects__object_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_tasks__task_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_tasks__task_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_tasks__task_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Task */
        post: operations["start_task_api_tasks__task_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_api_tasks__task_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition */
        post: operations["transition_api_tasks__task_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Task */
        post: operations["stop_task_api_tasks__task_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_tasks__task_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/tool_calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tool Call */
        post: operations["tool_call_api_tasks__task_id__tool_calls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_tasks__task_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_tasks__task_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/workspace/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace File */
        get: operations["workspace_file_api_tasks__task_id__workspace_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/workspace/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Tree */
        get: operations["workspace_tree_api_tasks__task_id__workspace_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptanceItem */
        AcceptanceItem: {
            /**
             * Desc
             * @description 文字描述的验收条件
             */
            desc: string;
            /**
             * Id
             * @description 验收条件编号
             */
            id: string;
        };
        /** AgentProfile */
        "AgentProfile-Input": {
            /**
             * Exec Image
             * @description 执行环境镜像
             */
            exec_image: string;
            /** @description 执行环境资源限制 */
            exec_resources: components["schemas"]["ExecResources"];
            /** @description 各任务类型模型与价格 */
            models: components["schemas"]["ModelSet-Input"];
            /** @description 默认调度参数 */
            params: components["schemas"]["Params-Input"];
            /**
             * Privileged Allowlist
             * @description 允许的提权命令前缀
             */
            privileged_allowlist?: string[];
            /** @description 该版本固定的提示词模板正文 */
            prompt_templates: components["schemas"]["PromptTemplates"];
            /** @description 提示词模板文件路径 */
            prompts: components["schemas"]["PromptPaths"];
        };
        /** AgentProfile */
        "AgentProfile-Output": {
            /**
             * Exec Image
             * @description 执行环境镜像
             */
            exec_image: string;
            /** @description 执行环境资源限制 */
            exec_resources: components["schemas"]["ExecResources"];
            /** @description 各任务类型模型与价格 */
            models: components["schemas"]["ModelSet-Output"];
            /** @description 默认调度参数 */
            params: components["schemas"]["Params-Output"];
            /**
             * Privileged Allowlist
             * @description 允许的提权命令前缀
             */
            privileged_allowlist?: string[];
            /** @description 该版本固定的提示词模板正文 */
            prompt_templates: components["schemas"]["PromptTemplates"];
            /** @description 提示词模板文件路径 */
            prompts: components["schemas"]["PromptPaths"];
        };
        /** AgentRegisterBody */
        AgentRegisterBody: {
            /** Close Mode */
            close_mode?: ("judge" | "final") | null;
            /**
             * Is Seed
             * @default false
             */
            is_seed: boolean;
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "explore" | "derive" | "close";
        };
        /** AgentRegistered */
        AgentRegistered: {
            /** Agent Id */
            agent_id: string;
            /** Token */
            token: string;
        };
        /** ArchiveBody */
        ArchiveBody: {
            /**
             * Fallback
             * @enum {string}
             */
            fallback: "none" | "agents-only";
            /** Size */
            size: number;
            /** Uri */
            uri: string;
        };
        /** Budget */
        Budget: {
            /**
             * Max Concurrent Agents
             * @description 并发探索和推导上限
             * @default 5
             */
            max_concurrent_agents: number;
            /**
             * Max Cost
             * @description 同价格表币种的金额上限
             */
            max_cost: number | string;
            /**
             * Max Minutes
             * @description 时间上限，分钟
             */
            max_minutes: number;
        };
        /** ClaimForBody */
        ClaimForBody: {
            /** Agent Id */
            agent_id: string;
            /** Intent Id */
            intent_id: string;
        };
        /** CloseBody */
        CloseBody: {
            /** Report */
            report?: string | null;
            /** Report Uri */
            report_uri?: string | null;
            /** Verdicts */
            verdicts: components["schemas"]["VerdictItem"][];
        };
        /** ConcludeBody */
        ConcludeBody: {
            /** Reason */
            reason: string;
        };
        /** Event */
        Event: {
            /**
             * Actor
             * @description 事件触发者
             */
            actor: string;
            /**
             * Addressed To
             * @description 点名目标，空值为广播
             */
            addressed_to?: string[] | null;
            /**
             * Created At
             * Format: date-time
             * @description 创建时间
             */
            created_at: string;
            /**
             * Object Id
             * @description 关联对象编号
             */
            object_id?: string | null;
            /**
             * Payload
             * @description 事件内容
             */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Task Id
             * Format: uuid
             * @description 所属任务
             */
            task_id: string;
            /** @description 事件类型 */
            type: components["schemas"]["EventType"];
            /**
             * Version
             * @description 全局递增版本
             */
            version: number;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "task.created" | "task.provisioning" | "task.running" | "task.closing" | "task.finished" | "task.failed" | "task.stopped" | "task.archived" | "fact.posted" | "fact.disputed" | "fact.undisputed" | "intent.posted" | "intent.claimed" | "intent.released" | "intent.closed" | "agent.spawned" | "agent.progress" | "agent.finished" | "agent.conclude_requested" | "derive.result" | "acceptance.judged" | "acceptance.reverted" | "task.report" | "budget.updated" | "tool_call.recorded";
        /** Evidence */
        Evidence: {
            /**
             * Auto
             * @description 是否由系统自动附加
             * @default false
             */
            auto: boolean;
            /**
             * Call Id
             * @description 产生证据的工具调用
             */
            call_id?: string | null;
            /**
             * Path
             * @description 执行环境内的原路径
             */
            path?: string | null;
            /**
             * Size
             * @description 证据字节数
             */
            size?: number | null;
            /**
             * Summary
             * @description 证据摘要
             */
            summary: string;
            /** @description 证据类型 */
            type: components["schemas"]["EvidenceType"];
            /**
             * Uri
             * @description 持久化后的对象 key
             */
            uri?: string | null;
        };
        /**
         * EvidenceType
         * @enum {string}
         */
        EvidenceType: "http" | "file" | "script" | "log" | "code_ref" | "text" | "command_output";
        /** ExecResources */
        ExecResources: {
            /**
             * Cpus
             * @description 执行环境 CPU 限额
             */
            cpus: number;
            /**
             * Mem
             * @description 执行环境内存限额
             */
            mem: string;
            /**
             * Pids
             * @description 执行环境进程限额
             */
            pids: number;
        };
        /**
         * FactKind
         * @enum {string}
         */
        FactKind: "observation" | "inference" | "structure";
        /** FinishBody */
        FinishBody: {
            /** End Reason */
            end_reason: string;
            /** Receipt */
            receipt: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatBody */
        HeartbeatBody: {
            /** Context Tokens */
            context_tokens: number;
            /** Last Seen Version */
            last_seen_version: number;
            /** Steps */
            steps: number;
            usage: components["schemas"]["Usage"];
        };
        /**
         * IntentResult
         * @enum {string}
         */
        IntentResult: "confirmed" | "rejected" | "inconclusive";
        /** LoginBody */
        LoginBody: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** ModelConfig */
        "ModelConfig-Input": {
            /**
             * Base Url
             * @description 模型接口地址
             */
            base_url: string;
            /**
             * Model
             * @description 模型名称
             */
            model: string;
            /** @description 模型价格表 */
            price: components["schemas"]["Price-Input"];
            /**
             * Provider
             * @description 模型供应商
             */
            provider: string;
            /**
             * Reasoning Effort
             * @description 推理强度
             */
            reasoning_effort: string;
        };
        /** ModelConfig */
        "ModelConfig-Output": {
            /**
             * Base Url
             * @description 模型接口地址
             */
            base_url: string;
            /**
             * Model
             * @description 模型名称
             */
            model: string;
            /** @description 模型价格表 */
            price: components["schemas"]["Price-Output"];
            /**
             * Provider
             * @description 模型供应商
             */
            provider: string;
            /**
             * Reasoning Effort
             * @description 推理强度
             */
            reasoning_effort: string;
        };
        /** ModelSet */
        "ModelSet-Input": {
            close: components["schemas"]["ModelConfig-Input"];
            derive: components["schemas"]["ModelConfig-Input"];
            explore: components["schemas"]["ModelConfig-Input"];
        };
        /** ModelSet */
        "ModelSet-Output": {
            close: components["schemas"]["ModelConfig-Output"];
            derive: components["schemas"]["ModelConfig-Output"];
            explore: components["schemas"]["ModelConfig-Output"];
        };
        /** Params */
        "Params-Input": {
            /**
             * Close Reserve Ratio
             * @description 总预算中为收尾预留的比例
             * @default 0.05
             */
            close_reserve_ratio: number | string;
            /**
             * Conclude Grace Calls
             * @description 结束指令后的交接工具调用次数
             * @default 3
             */
            conclude_grace_calls: number;
            /**
             * Context Threshold
             * @description 触发探索交接的上下文 token 数
             * @default 128000
             */
            context_threshold: number;
            /**
             * Delta Max Lines
             * @description 增量推送最大行数
             * @default 15
             */
            delta_max_lines: number;
            /**
             * Derive Empty Limit
             * @description 连续空推导次数上限
             * @default 2
             */
            derive_empty_limit: number;
            /**
             * Derive Enabled
             * @description 探索静止且裁定后是否继续推导
             * @default true
             */
            derive_enabled: boolean;
            /**
             * Dispute Notify Depth
             * @description 争议点名最大深度
             * @default 2
             */
            dispute_notify_depth: number;
            /**
             * Explore Max Steps
             * @description 单次探索最多模型调用数
             * @default 60
             */
            explore_max_steps: number;
            /**
             * Grace Timeout
             * @description 结束宽限时长，分钟
             * @default 5
             */
            grace_timeout: number;
            /**
             * Heartbeat Timeout
             * @description 模型调用心跳超时，分钟
             * @default 30
             */
            heartbeat_timeout: number;
            /**
             * Intent Max Attempts
             * @description 意图未关闭时可被尝试的次数
             * @default 3
             */
            intent_max_attempts: number;
            /**
             * Max Consecutive Failures
             * @description 连续运行错误上限
             * @default 3
             */
            max_consecutive_failures: number;
            /**
             * Seed Max Steps
             * @description 种子未认领意图的最大步数
             * @default 20
             */
            seed_max_steps: number;
            /**
             * Snapshot Max Lines
             * @description YAML 快照最大行数
             * @default 150
             */
            snapshot_max_lines: number;
        };
        /** Params */
        "Params-Output": {
            /**
             * Close Reserve Ratio
             * @description 总预算中为收尾预留的比例
             * @default 0.05
             */
            close_reserve_ratio: string;
            /**
             * Conclude Grace Calls
             * @description 结束指令后的交接工具调用次数
             * @default 3
             */
            conclude_grace_calls: number;
            /**
             * Context Threshold
             * @description 触发探索交接的上下文 token 数
             * @default 128000
             */
            context_threshold: number;
            /**
             * Delta Max Lines
             * @description 增量推送最大行数
             * @default 15
             */
            delta_max_lines: number;
            /**
             * Derive Empty Limit
             * @description 连续空推导次数上限
             * @default 2
             */
            derive_empty_limit: number;
            /**
             * Derive Enabled
             * @description 探索静止且裁定后是否继续推导
             * @default true
             */
            derive_enabled: boolean;
            /**
             * Dispute Notify Depth
             * @description 争议点名最大深度
             * @default 2
             */
            dispute_notify_depth: number;
            /**
             * Explore Max Steps
             * @description 单次探索最多模型调用数
             * @default 60
             */
            explore_max_steps: number;
            /**
             * Grace Timeout
             * @description 结束宽限时长，分钟
             * @default 5
             */
            grace_timeout: number;
            /**
             * Heartbeat Timeout
             * @description 模型调用心跳超时，分钟
             * @default 30
             */
            heartbeat_timeout: number;
            /**
             * Intent Max Attempts
             * @description 意图未关闭时可被尝试的次数
             * @default 3
             */
            intent_max_attempts: number;
            /**
             * Max Consecutive Failures
             * @description 连续运行错误上限
             * @default 3
             */
            max_consecutive_failures: number;
            /**
             * Seed Max Steps
             * @description 种子未认领意图的最大步数
             * @default 20
             */
            seed_max_steps: number;
            /**
             * Snapshot Max Lines
             * @description YAML 快照最大行数
             * @default 150
             */
            snapshot_max_lines: number;
        };
        /** PostFactRequest */
        PostFactRequest: {
            /** Derived From */
            derived_from?: string[];
            /** Disputes */
            disputes?: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            kind: components["schemas"]["FactKind"];
            /** Resolves */
            resolves?: string | null;
            result?: components["schemas"]["IntentResult"] | null;
            /** Satisfies */
            satisfies?: string[];
            /** Statement */
            statement: string;
        };
        /** PostIntentRequest */
        PostIntentRequest: {
            /** Based On */
            based_on: string[];
            /**
             * Claim
             * @default false
             */
            claim: boolean;
            /** Expected */
            expected: string;
            /** Method */
            method: string;
            /** Relates To */
            relates_to: string[];
            /** Retry Of */
            retry_of?: string | null;
            /** Statement */
            statement: string;
        };
        /** Price */
        "Price-Input": {
            /**
             * Cache Hit Per M
             * @description 每百万缓存命中输入 token 单价
             */
            cache_hit_per_m?: number | string | null;
            /**
             * Cache Miss Per M
             * @description 每百万缓存未命中输入 token 单价
             */
            cache_miss_per_m?: number | string | null;
            /**
             * Currency
             * @description 计价币种
             */
            currency?: string | null;
            /**
             * Off Peak
             * @description 是否启用错峰价格
             */
            off_peak?: boolean | null;
            /**
             * Output Per M
             * @description 每百万输出 token 单价
             */
            output_per_m?: number | string | null;
        };
        /** Price */
        "Price-Output": {
            /**
             * Cache Hit Per M
             * @description 每百万缓存命中输入 token 单价
             */
            cache_hit_per_m?: string | null;
            /**
             * Cache Miss Per M
             * @description 每百万缓存未命中输入 token 单价
             */
            cache_miss_per_m?: string | null;
            /**
             * Currency
             * @description 计价币种
             */
            currency?: string | null;
            /**
             * Off Peak
             * @description 是否启用错峰价格
             */
            off_peak?: boolean | null;
            /**
             * Output Per M
             * @description 每百万输出 token 单价
             */
            output_per_m?: string | null;
        };
        /** ProfileDocument */
        ProfileDocument: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /** Name */
            name: string;
            profile: components["schemas"]["AgentProfile-Output"];
            /** Version */
            version: number;
        };
        /** ProfileName */
        ProfileName: {
            /** Latest Version */
            latest_version: number;
            /** Name */
            name: string;
        };
        /** ProfileVersion */
        ProfileVersion: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** PromptPaths */
        PromptPaths: {
            /**
             * Close
             * @description 收尾提示词模板路径
             */
            close: string;
            /**
             * Derive
             * @description 推导提示词模板路径
             */
            derive: string;
            /**
             * Explore
             * @description 探索提示词模板路径
             */
            explore: string;
        };
        /** PromptTemplates */
        PromptTemplates: {
            /**
             * Close
             * @description 收尾提示词模板正文快照
             */
            close: string;
            /**
             * Derive
             * @description 推导提示词模板正文快照
             */
            derive: string;
            /**
             * Explore
             * @description 探索提示词模板正文快照
             */
            explore: string;
        };
        /** ReleaseBody */
        ReleaseBody: {
            /** Note */
            note: string;
        };
        /** SearchHit */
        SearchHit: {
            /** Id */
            id: string;
            /** Statement */
            statement: string;
            /**
             * Type
             * @enum {string}
             */
            type: "fact" | "intent";
        };
        /** StatusBody */
        StatusBody: {
            /** Reason */
            reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "closing" | "finished" | "failed" | "stopped";
        };
        /** StatusResult */
        StatusResult: {
            /** Events */
            events?: {
                [key: string]: unknown;
            }[];
            /** Status */
            status: string;
        };
        /** TaskCreateBody */
        TaskCreateBody: {
            /**
             * Acceptance
             * @description 文字验收条件
             */
            acceptance: components["schemas"]["AcceptanceItem"][];
            /**
             * Agent Profile
             * @description Agent 配置名称
             */
            agent_profile: string;
            /** @description 金额、时长和并发预算 */
            budget: components["schemas"]["Budget"];
            /**
             * Domain Context
             * @description 领域提示
             */
            domain_context?: string | null;
            /**
             * Egress Allowlist
             * @description 任务希望访问的域名（仅记录，不限制默认直连）
             */
            egress_allowlist?: string[];
            /**
             * Goal
             * @description 任务目标
             */
            goal: string;
            /**
             * Params
             * @description Agent 配置参数覆盖
             */
            params?: {
                [key: string]: number | string | boolean;
            };
            /** Profile Version */
            profile_version?: number | null;
        };
        /** TaskCreated */
        TaskCreated: {
            /** Agent Profile */
            agent_profile: string;
            /** Agent Profile Version */
            agent_profile_version: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** TaskView */
        TaskView: {
            /** Acceptance State */
            acceptance_state: {
                [key: string]: unknown;
            };
            /** Agent Profile */
            agent_profile: string;
            /** Agent Profile Version */
            agent_profile_version: number;
            /** Agents */
            agents: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Goal */
            goal: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Report Uri */
            report_uri: string | null;
            /** Status */
            status: string;
            /** Usage */
            usage: {
                [key: string]: unknown;
            };
            /** Workspace Uri */
            workspace_uri: string | null;
        };
        /** ToolCallBody */
        ToolCallBody: {
            /** Agent Id */
            agent_id: string;
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Result Head */
            result_head?: string | null;
            /** Result Uri */
            result_uri?: string | null;
            /** Tool */
            tool: string;
        };
        /** UploadResult */
        UploadResult: {
            /** Key */
            key: string;
            /** Size */
            size: number;
        };
        /** Usage */
        Usage: {
            /**
             * Cache Hit Tokens
             * @description 缓存命中输入 token
             * @default 0
             */
            cache_hit_tokens: number;
            /**
             * Cache Miss Tokens
             * @description 缓存未命中输入 token
             * @default 0
             */
            cache_miss_tokens: number;
            /**
             * Cost
             * @description 金额成本
             * @default 0
             */
            cost: number | string;
            /**
             * Output Tokens
             * @description 输出 token
             * @default 0
             */
            output_tokens: number;
            /**
             * Reasoning Tokens
             * @description 推理 token
             * @default 0
             */
            reasoning_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "met" | "unmet";
        /** VerdictItem */
        VerdictItem: {
            /**
             * Evidence Facts
             * @description 支撑事实
             */
            evidence_facts?: string[];
            /**
             * Id
             * @description 验收条件编号
             */
            id: string;
            /**
             * Missing
             * @description 未满足时的行动缺口
             */
            missing?: string | null;
            /**
             * Reason
             * @description 裁定理由
             */
            reason: string;
            /** @description 满足或未满足 */
            verdict: components["schemas"]["Verdict"];
        };
        /** WorkspaceEntryView */
        WorkspaceEntryView: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "file" | "directory" | "link";
            /** Path */
            path: string;
            /** Size */
            size: number;
        };
        /** WorkspaceFileView */
        WorkspaceFileView: {
            /** Binary */
            binary: boolean;
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Text */
            text: string;
            /** Truncated */
            truncated: boolean;
        };
        /** WorkspaceTreeView */
        WorkspaceTreeView: {
            /** Entries */
            entries: components["schemas"]["WorkspaceEntryView"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    evidence_api_evidence_get: {
        parameters: {
            query: {
                uri: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileName"][];
                };
            };
        };
    };
    profile_versions_api_profiles__name__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_version_api_profiles__name__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentProfile-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_version_api_profiles__name__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_detail_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_agent_api_tasks__task_id__agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRegisterBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRegistered"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_api_tasks__task_id__agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conclude_api_tasks__task_id__agents__agent_id__conclude_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConcludeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_api_tasks__task_id__agents__agent_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grace_api_tasks__task_id__agents__agent_id__grace_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_archive_api_tasks__task_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_for_api_tasks__task_id__claim_for_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimForBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_api_tasks__task_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_tasks__task_id__events_get: {
        parameters: {
            query?: {
                since?: number;
                for?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_fact_api_tasks__task_id__facts_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostFactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_intent_api_tasks__task_id__intents_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
                claim?: boolean | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_api_tasks__task_id__intents__intent_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_api_tasks__task_id__intents__intent_id__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_close_api_tasks__task_id__intents__intent_id__system_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_api_tasks__task_id__objects__object_id__get: {
        parameters: {
            query?: {
                depth?: number;
            };
            header?: never;
            path: {
                task_id: string;
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_tasks__task_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_tasks__task_id__search_get: {
        parameters: {
            query?: {
                q?: string | null;
                k?: number;
                type?: "fact" | "intent" | "all";
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_tasks__task_id__snapshot_get: {
        parameters: {
            query?: {
                format?: "yaml";
                max_lines?: number | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_task_api_tasks__task_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    state_api_tasks__task_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_api_tasks__task_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_task_api_tasks__task_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_tasks__task_id__stream_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_call_api_tasks__task_id__tool_calls_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolCallBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_tasks__task_id__uploads_post: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_api_tasks__task_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_file_api_tasks__task_id__workspace_file_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceFileView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_tree_api_tasks__task_id__workspace_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceTreeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
