import { expect, test } from '@playwright/test';
import { installMockApi } from './fixtures';

test('模型上下文容量保存、回显与清除，浏览器阻止小数', async ({ page }) => {
  const mock = await installMockApi(page);
  await page.goto('/profiles');
  await page.getByRole('button', { name: '模型配置', exact: true }).click();
  await page.getByRole('button', { name: /审查模型/ }).click();
  const input = page.getByLabel('上下文大小（token）');
  await expect(input).toBeEmpty();
  await input.fill('500000');
  await expect(page.getByText(/新任务交接阈值 400,000/)).toBeVisible();
  await page.getByRole('button', { name: '保存', exact: true }).click();
  expect(mock.modelSaves[0]).toMatchObject({ context_window: 500000 });
  await expect(input).toHaveValue('500000');
  await input.fill('1.5');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  expect(mock.modelSaves).toHaveLength(1);
  await input.fill('');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  expect(mock.modelSaves[1]).toMatchObject({ context_window: null });
  expect(mock.unexpected).toEqual([]);
});

test('配置布局、键盘角色切换、草稿保护及各入口窄屏显示', async ({ page }) => {
  const mock = await installMockApi(page);
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.goto('/profiles');
  const prompt = page.getByLabel('完整系统提示词');
  await prompt.fill('# 工作职责\n\n围绕用户目标开展调查，将可复核的发现及时发布到共享黑板。\n\n## 调查与协作\n\n- 开始前阅读任务目标、验收条件和当前黑板。\n- 证据充分后提交 Fact，说明来源与依据。\n- 发现独立方向时提出 Intent，供其他 Agent 认领。\n- 遇到结束指令，整理证据、发布发现并完成交接。\n\n## 当前任务\n\n{{ goal }}\n\n{{ acceptance_status }}');
  const explore = page.getByRole('tab', { name: /Explore/ });
  await explore.focus();
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('tab', { name: /Derive/ })).toBeFocused();
  await page.keyboard.press('Home');
  await expect(prompt).toContainText('工作职责');
  await page.screenshot({ path: '../.data/checkpoints/agent-settings/worker-desktop.png', fullPage: true });
  page.once('dialog', (dialog) => dialog.dismiss());
  await page.getByRole('button', { name: '模型配置', exact: true }).click();
  await expect(prompt).toBeVisible();
  await page.getByRole('button', { name: '保存并应用' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  await page.screenshot({ path: '../.data/checkpoints/agent-settings/worker-mobile.png', fullPage: true });
  await page.getByRole('button', { name: '模型配置', exact: true }).click();
  await page.getByRole('button', { name: /审查模型/ }).click();
  await page.getByLabel('上下文大小（token）').fill('500000');
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  await page.screenshot({ path: '../.data/checkpoints/agent-settings/models-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.screenshot({ path: '../.data/checkpoints/agent-settings/models-desktop.png', fullPage: true });
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByRole('button', { name: 'MCP 工具', exact: true }).click();
  await page.getByRole('button', { name: /资料检索/ }).click();
  await page.screenshot({ path: '../.data/checkpoints/agent-settings/mcp-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  expect(mock.unexpected).toEqual([]);
});
